// --- BEREINIGTE DATEN (Ohne Base64 Strings) ---
window.MATERIALS = [
  // Food (Fire focused)
  {
    id: 517,
    name: "Meat",
    type: "Food",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 580,
    name: "Bread",
    type: "Food",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 553,
    name: "Bao",
    type: "Food",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 539,
    name: "Piece of Cake",
    type: "Food",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40000,
    name: "Alchemic Food (Red)",
    type: "Food",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Food (Earth focused)
  {
    id: 535,
    name: "Pumpkin",
    type: "Food",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 581,
    name: "Edible Mushroom",
    type: "Food",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 508,
    name: "Yellow Herb",
    type: "Food",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 549,
    name: "Yam",
    type: "Food",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40001,
    name: "Alchemic Food (Green)",
    type: "Food",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Food (Air focused)
  {
    id: 513,
    name: "Banana",
    type: "Food",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 577,
    name: "Bag of Grain",
    type: "Food",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 520,
    name: "Hinalle Leaflet",
    type: "Food",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 550,
    name: "Rice Cake",
    type: "Food",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40002,
    name: "Alchemic Food (White)",
    type: "Food",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Food (Water focused)
  {
    id: 512,
    name: "Apple",
    type: "Food",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 579,
    name: "Fresh Fish",
    type: "Food",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 518,
    name: "Honey",
    type: "Food",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 521,
    name: "Aloe Leaflet",
    type: "Food",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40003,
    name: "Alchemic Food (Blue)",
    type: "Food",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },

  // Wood (Fire focused)
  {
    id: 1033,
    name: "Maneater Root",
    type: "Wood",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 1003,
    name: "Coal",
    type: "Wood",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 7068,
    name: "Burnt Tree",
    type: "Wood",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 7098,
    name: "Live Coal",
    type: "Wood",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40004,
    name: "Everdry Plant",
    type: "Wood",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Wood (Earth focused)
  {
    id: 1019,
    name: "Trunk",
    type: "Wood",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 7188,
    name: "Brown Root",
    type: "Wood",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 7201,
    name: "Log",
    type: "Wood",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 7196,
    name: "Shoulder Protector",
    type: "Wood",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40005,
    name: "Tea Plant",
    type: "Wood",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Wood (Air focused)
  {
    id: 1026,
    name: "Acorn",
    type: "Wood",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 7203,
    name: "Strong Branch",
    type: "Wood",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 7195,
    name: "Slingshot",
    type: "Wood",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 7299,
    name: "Straw Basket",
    type: "Wood",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40006,
    name: "Fragrant Plant",
    type: "Wood",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Wood (Water focused)
  {
    id: 902,
    name: "Tree Root",
    type: "Wood",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 930,
    name: "Rotten Bandage",
    type: "Wood",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 7218,
    name: "Decomposed Rope",
    type: "Wood",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 7266,
    name: "Denture from Dragon Mask",
    type: "Wood",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40007,
    name: "Poisonous Plant",
    type: "Wood",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },

  // Sand (Fire focused)
  {
    id: 7456,
    name: "Red Spice",
    type: "Sand",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 1056,
    name: "Grit",
    type: "Sand",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 7041,
    name: "Fine Grit",
    type: "Sand",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 7096,
    name: "Lava",
    type: "Sand",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40008,
    name: "Warmth Powder",
    type: "Sand",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Sand (Earth focused)
  {
    id: 7452,
    name: "Yellow Spice",
    type: "Sand",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 7264,
    name: "Dry Sand",
    type: "Sand",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 7043,
    name: "Fine Sand",
    type: "Sand",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 7067,
    name: "Stone Fragment",
    type: "Sand",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40009,
    name: "Refined Powder",
    type: "Sand",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Sand (Air focused)
  {
    id: 7154,
    name: "Poisonous Powder",
    type: "Sand",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 924,
    name: "Powder of Butterfly",
    type: "Sand",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 1057,
    name: "Moth Dust",
    type: "Sand",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 7001,
    name: "Mould Powder",
    type: "Sand",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40010,
    name: "Aromatic Powder",
    type: "Sand",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Sand (Water focused)
  {
    id: 7004,
    name: "Mud Lump",
    type: "Sand",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 7124,
    name: "Sand Clump",
    type: "Sand",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 7149,
    name: "Yellow Plate",
    type: "Sand",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 7158,
    name: "Broken Liquor Jar",
    type: "Sand",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40011,
    name: "Chilling Powder",
    type: "Sand",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },

  // Beast (Fire focused)
  {
    id: 919,
    name: "Animal Skin",
    type: "Beast",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 1036,
    name: "Dragon Scale",
    type: "Beast",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 1022,
    name: "Nine Tails",
    type: "Beast",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 7009,
    name: "Glitter Shell",
    type: "Beast",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40012,
    name: "Magmaring Spark",
    type: "Beast",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Beast (Earth focused)
  {
    id: 1062,
    name: "Jack o' Pumpkin",
    type: "Beast",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 1012,
    name: "Frill",
    type: "Beast",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 1096,
    name: "Round Shell",
    type: "Beast",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 7155,
    name: "Poisonous Toad Skin",
    type: "Beast",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40013,
    name: "Stapo Spark",
    type: "Beast",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Beast (Air focused)
  {
    id: 7106,
    name: "Antelope Horn",
    type: "Beast",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 7101,
    name: "Peco Peco Feather",
    type: "Beast",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 7168,
    name: "Giant Butterfly Wing",
    type: "Beast",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 7116,
    name: "Harpy Talon",
    type: "Beast",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40014,
    name: "Poporing Spark",
    type: "Beast",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Beast (Water focused)
  {
    id: 1052,
    name: "Single Cell",
    type: "Beast",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 959,
    name: "Stinky Scale",
    type: "Beast",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 1015,
    name: "Tongue",
    type: "Beast",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 702,
    name: "Animal Gore",
    type: "Beast",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40015,
    name: "Pouring Spark",
    type: "Beast",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },

  // Alloy (Fire focused)
  {
    id: 1041,
    name: "Lantern",
    type: "Alloy",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 7319,
    name: "Used Iron Plate",
    type: "Alloy",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 7120,
    name: "Burning Horseshoe",
    type: "Alloy",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 7512,
    name: "Burnt Part",
    type: "Alloy",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40016,
    name: "Precious Steel",
    type: "Alloy",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Alloy (Earth focused)
  {
    id: 1010,
    name: "Phracon",
    type: "Alloy",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 1002,
    name: "Iron Ore",
    type: "Alloy",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 7016,
    name: "Spoon Stub",
    type: "Alloy",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 7095,
    name: "Metal Fragment",
    type: "Alloy",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40017,
    name: "Fusion Alloy",
    type: "Alloy",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Alloy (Air focused)
  {
    id: 7215,
    name: "Broken Needle",
    type: "Alloy",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 7156,
    name: "Broken Shuriken",
    type: "Alloy",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 7214,
    name: "Bat Cage",
    type: "Alloy",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 7072,
    name: "Old Shuriken",
    type: "Alloy",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40018,
    name: "Metallic Gas",
    type: "Alloy",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Alloy (Water focused)
  {
    id: 7317,
    name: "Rusty Screw",
    type: "Alloy",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 941,
    name: "Nose Ring",
    type: "Alloy",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 7208,
    name: "Rusty Kitchen Knife",
    type: "Alloy",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 1064,
    name: "Reins",
    type: "Alloy",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40019,
    name: "Quicksilver",
    type: "Alloy",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },

  // Magic (Fire focused)
  {
    id: 1000,
    name: "Star Crumb",
    type: "Magic",
    quality: 10,
    fire: 100,
    earth: 25,
    air: 50,
    water: 75,
  },
  {
    id: 7097,
    name: "Burning Heart",
    type: "Magic",
    quality: 30,
    fire: 80,
    earth: 20,
    air: 40,
    water: 60,
  },
  {
    id: 923,
    name: "Evil Horn",
    type: "Magic",
    quality: 50,
    fire: 60,
    earth: 15,
    air: 30,
    water: 45,
  },
  {
    id: 7099,
    name: "Worn-out Magic Scroll",
    type: "Magic",
    quality: 70,
    fire: 40,
    earth: 10,
    air: 20,
    water: 30,
  },
  {
    id: 40020,
    name: "Fire Core",
    type: "Magic",
    quality: 90,
    fire: 20,
    earth: 5,
    air: 10,
    water: 15,
  },
  // Magic (Earth focused)
  {
    id: 911,
    name: "Scell",
    type: "Magic",
    quality: 10,
    fire: 75,
    earth: 100,
    air: 25,
    water: 50,
  },
  {
    id: 953,
    name: "Stone Heart",
    type: "Magic",
    quality: 30,
    fire: 60,
    earth: 80,
    air: 20,
    water: 40,
  },
  {
    id: 7321,
    name: "Crystal Fragment",
    type: "Magic",
    quality: 50,
    fire: 45,
    earth: 60,
    air: 15,
    water: 30,
  },
  {
    id: 7117,
    name: "Torn Magic Book",
    type: "Magic",
    quality: 70,
    fire: 30,
    earth: 40,
    air: 10,
    water: 20,
  },
  {
    id: 40021,
    name: "Earth Core",
    type: "Magic",
    quality: 90,
    fire: 15,
    earth: 20,
    air: 5,
    water: 10,
  },
  // Magic (Air focused)
  {
    id: 912,
    name: "Zargon",
    type: "Magic",
    quality: 10,
    fire: 50,
    earth: 75,
    air: 100,
    water: 25,
  },
  {
    id: 7189,
    name: "Wooden Heart",
    type: "Magic",
    quality: 30,
    fire: 40,
    earth: 60,
    air: 80,
    water: 20,
  },
  {
    id: 7263,
    name: "Cat's Eye",
    type: "Magic",
    quality: 50,
    fire: 30,
    earth: 45,
    air: 60,
    water: 15,
  },
  {
    id: 7162,
    name: "Cloud Crumb",
    type: "Magic",
    quality: 70,
    fire: 20,
    earth: 30,
    air: 40,
    water: 10,
  },
  {
    id: 40022,
    name: "Air Core",
    type: "Magic",
    quality: 90,
    fire: 10,
    earth: 15,
    air: 20,
    water: 5,
  },
  // Magic (Water focused)
  {
    id: 910,
    name: "Garlet",
    type: "Magic",
    quality: 10,
    fire: 25,
    earth: 50,
    air: 75,
    water: 100,
  },
  {
    id: 7220,
    name: "Ectoplasm",
    type: "Magic",
    quality: 30,
    fire: 20,
    earth: 40,
    air: 60,
    water: 80,
  },
  {
    id: 7066,
    name: "Ice Cubic",
    type: "Magic",
    quality: 50,
    fire: 15,
    earth: 30,
    air: 45,
    water: 60,
  },
  {
    id: 609,
    name: "Amulet",
    type: "Magic",
    quality: 70,
    fire: 10,
    earth: 20,
    air: 30,
    water: 40,
  },
  {
    id: 40023,
    name: "Water Core",
    type: "Magic",
    quality: 90,
    fire: 5,
    earth: 10,
    air: 15,
    water: 20,
  },
];
