window.RECIPES_BASIC = [
  // --- BASIC RECIPES ---
  // [ Food ] -> [ Food ]
  {
    id: 40000,
    product: "Alchemic Food (Red)",
    type: "Food",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Food", "Food"],
    catalyst: "none",
    element: "Fire",
  },
  {
    id: 40001,
    product: "Alchemic Food (Green)",
    type: "Food",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Wood", "Food"],
    catalyst: "none",
    element: "Earth",
  },
  {
    id: 40002,
    product: "Alchemic Food (White)",
    type: "Food",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Wood", "Food", "Wood"],
    catalyst: "none",
    element: "Air",
  },
  {
    id: 40003,
    product: "Alchemic Food (Blue)",
    type: "Food",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Wood", "Wood", "Food"],
    catalyst: "none",
    element: "Water",
  },

  // [ Food ] -> [ Poison ]
  {
    id: 40024,
    product: "Charming Potion",
    type: "Poison",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Wood", "Beast"],
    catalyst: "Red Gemstone",
    element: "Fire",
  },
  {
    id: 40025,
    product: "Alchemic Antidote",
    type: "Poison",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Sand", "Alloy", "Magic"],
    catalyst: "Red Gemstone",
    element: "Earth",
  },
  {
    id: 40026,
    product: "Pesticide Kit",
    type: "Poison",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Sand", "Wood", "Food"],
    catalyst: "Red Gemstone",
    element: "Air",
  },
  {
    id: 40027,
    product: "Demon Blood",
    type: "Poison",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Beast", "Beast", "Wood"],
    catalyst: "Red Gemstone",
    element: "Water",
  },

  // [ Food ] -> [ Heal ]
  {
    id: 40028,
    product: "Basic Potion",
    type: "Heal",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Food", "Food"],
    catalyst: "Cyfar",
    element: "Fire",
  },
  {
    id: 40029,
    product: "Royal Black Tea",
    type: "Heal",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Sand", "Sand", "Sand"],
    catalyst: "Cyfar",
    element: "Earth",
  },
  {
    id: 40030,
    product: "Jelly Potion",
    type: "Heal",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Sand", "Wood", "Food"],
    catalyst: "Cyfar",
    element: "Air",
  },
  {
    id: 40031,
    product: "Psychic Potion",
    type: "Heal",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Wood", "Food", "Food"],
    catalyst: "Cyfar",
    element: "Water",
  },

  // [ Food ] -> [ Tonic ]
  {
    id: 40032,
    product: "Power Tonic",
    type: "Tonic",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Beast", "Wood", "Beast"],
    catalyst: "Yellow Gemstone",
    element: "Fire",
  },
  {
    id: 40033,
    product: "Vigor Tonic",
    type: "Tonic",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Sand", "Beast"],
    catalyst: "Yellow Gemstone",
    element: "Earth",
  },
  {
    id: 40034,
    product: "Acceleration Tonic",
    type: "Tonic",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Beast", "Beast", "Beast"],
    catalyst: "Yellow Gemstone",
    element: "Air",
  },
  {
    id: 40035,
    product: "Magic Tonic",
    type: "Tonic",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Wood", "Magic", "Food"],
    catalyst: "Yellow Gemstone",
    element: "Water",
  },

  // [ Food ] -> [ Condiment ]
  {
    id: 40036,
    product: "Pepper X Sauce",
    type: "Condiment",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Sand", "Beast"],
    catalyst: "Blue Gemstone",
    element: "Fire",
  },
  {
    id: 40037,
    product: "Ajvar",
    type: "Condiment",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Sand", "Sand"],
    catalyst: "Blue Gemstone",
    element: "Earth",
  },
  {
    id: 40038,
    product: "Preserved Lemon",
    type: "Condiment",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Sand", "Alloy", "Wood"],
    catalyst: "Blue Gemstone",
    element: "Air",
  },
  {
    id: 40039,
    product: "Grape Jam",
    type: "Condiment",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Food", "Food", "Food", "Magic"],
    catalyst: "Blue Gemstone",
    element: "Water",
  },

  // [ Wood ] -> [ Wood ]
  {
    id: 40004,
    product: "Everdry Plant",
    type: "Wood",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Food", "Wood"],
    catalyst: "none",
    element: "Fire",
  },
  {
    id: 40005,
    product: "Tea Plant",
    type: "Wood",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Wood", "Wood"],
    catalyst: "none",
    element: "Earth",
  },
  {
    id: 40006,
    product: "Fragrant Plant",
    type: "Wood",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Wood", "Food", "Food"],
    catalyst: "none",
    element: "Air",
  },
  {
    id: 40007,
    product: "Poisonous Plant",
    type: "Wood",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Wood", "Food"],
    catalyst: "none",
    element: "Water",
  },

  // [ Wood ] -> [ Fuel ]
  {
    id: 40040,
    product: "Everlasting Fuel",
    type: "Fuel",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Beast", "Food", "Beast"],
    catalyst: "Red Gemstone",
    element: "Fire",
  },
  {
    id: 40041,
    product: "Black Gold",
    type: "Fuel",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Sand", "Beast", "Sand"],
    catalyst: "Red Gemstone",
    element: "Earth",
  },
  {
    id: 40042,
    product: "Flammable Gas",
    type: "Fuel",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Beast", "Food", "Wood"],
    catalyst: "Red Gemstone",
    element: "Air",
  },
  {
    id: 40043,
    product: "Synthetic Oil",
    type: "Fuel",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Sand", "Beast", "Wood"],
    catalyst: "Red Gemstone",
    element: "Water",
  },

  // [ Wood ] -> [ Dye ]
  {
    id: 40044,
    product: "Magenta Pigment",
    type: "Dye",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Sand", "Magic"],
    catalyst: "Cyfar",
    element: "Fire",
  },
  {
    id: 40045,
    product: "Shade Pigment",
    type: "Dye",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Sand", "Alloy"],
    catalyst: "Cyfar",
    element: "Earth",
  },
  {
    id: 40046,
    product: "Yellow Pigment",
    type: "Dye",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Sand", "Sand"],
    catalyst: "Cyfar",
    element: "Air",
  },
  {
    id: 40047,
    product: "Cyan Pigment",
    type: "Dye",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Sand", "Beast"],
    catalyst: "Cyfar",
    element: "Water",
  },

  // [ Wood ] -> [ Tool ]
  {
    id: 40048,
    product: "Alchemist's Hammer",
    type: "Tool",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Sand", "Beast", "Food"],
    catalyst: "Yellow Gemstone",
    element: "Fire",
  },
  {
    id: 40049,
    product: "Sand Shovel",
    type: "Tool",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Wood", "Food", "Wood"],
    catalyst: "Yellow Gemstone",
    element: "Earth",
  },
  {
    id: 40050,
    product: "Scouter",
    type: "Tool",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Wood", "Sand", "Wood"],
    catalyst: "Yellow Gemstone",
    element: "Air",
  },
  {
    id: 40051,
    product: "Alchemist's Grimoire",
    type: "Tool",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Beast", "Alloy", "Sand"],
    catalyst: "Yellow Gemstone",
    element: "Water",
  },

  // [ Wood ] -> [ Paper ]
  {
    id: 40052,
    product: "Baking Sheet Paper",
    type: "Paper",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Food", "Sand", "Food"],
    catalyst: "Blue Gemstone",
    element: "Fire",
  },
  {
    id: 40053,
    product: "High Quality Paper",
    type: "Paper",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Wood", "Wood", "Food"],
    catalyst: "Blue Gemstone",
    element: "Earth",
  },
  {
    id: 40054,
    product: "Decorative Paper",
    type: "Paper",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Beast", "Wood", "Wood"],
    catalyst: "Blue Gemstone",
    element: "Air",
  },
  {
    id: 40055,
    product: "Enchanted Paper",
    type: "Paper",
    rank: "Basic",
    minQuality: 0,
    ingredients: ["Wood", "Sand", "Magic", "Wood"],
    catalyst: "Blue Gemstone",
    element: "Water",
  },
];
